# Generated by Django 5.0.4 on 2024-05-21 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_patient'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
