# Generated by Django 5.0.4 on 2024-05-22 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='report',
            field=models.DateField(),
        ),
    ]
