# Generated by Django 5.0.4 on 2024-05-24 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_patient_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.FileField(upload_to='Doctore'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='image',
            field=models.FileField(upload_to='Patient'),
        ),
    ]
