# Generated by Django 5.0.4 on 2024-05-24 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_doctor_image_alter_patient_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='Patient'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='mobileno',
            field=models.IntegerField(),
        ),
    ]
