# Generated by Django 5.0.4 on 2024-05-25 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_doctor_mobileno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='mobileno',
            field=models.BigIntegerField(),
        ),
    ]
